export default {
    "getIpfsUrl": "example:dbchain.getIpfsUrl(cid='')；\n desc:获取ipfs地址(上传的文件地址前缀)",
    "restGet": "example:dbchain.restGet(url)；\n desc:发出get请求，一个基于axios的get请求方法",
    "hasKey": "example:dbchain.hasKey()；\n desc:判断当前环境是否有基本账号信息（pubKey,priKey,address）",
    "hasPassphrase": "example:dbchain.hasPassphrase()；\n desc:判断当前环境是否有密码(密码用于验证加密是否正确)",
    "savePassphrase": "example:dbchain.savePassphrase(Passphrase)；\n desc:设置密码",
    "removePassphrase": "example:dbchain.removePassphrase(Passphrase)；\n desc:移除密码（密码移除会导致验证账号私钥失败，将不可操作，常用于用户退出登录时移除用户密码）",
    "newMnemonic": "example:dbchain.newMnemonic()；\n desc:生成一个新的助记词",
    "getPassphrase": "example:dbchain.getPassphrase()；\n desc:获取用户目前的密码",
    "validateMnemonic": "example:dbchain.validateMnemonic(Mnemonic)；\n desc:验证助记词是否合法",
    "createAndStoreKey": "example:dbchain.createAndStoreKey(mnemonic, passphrase)；\n desc:根据助记词生成对应公钥私钥地址",
    "getPrivKey": "example:dbchain.getPrivKey()；\n desc:获取当前用户的私钥",
    "getPubKey": "example:dbchain.getPubKey()；\n desc:获取当前用户的公钥",
    "getAddress": "example:dbchain.getAddress()；\n desc:获取当前用户的地址",
    "checkChainId": "example:dbchain.checkChainId(chainId)；\n desc:验证当前chainId是否可以使用 \n 异步",
    "getAccount": "example:dbchain.getAccount(address)；\n desc:获取指定地址在当前链拥有的积分",
    "insertRow": "example:dbchain.insertRow(appCode, tableName, data, callback)；\n desc:指定库指定表中插入指定数据 \n data:{'字段名':'字段值',...} callback:function(){// 执行之后的回调}",
    "canInsertRow": "example:dbchain.canInsertRow(appCode, tableName, data)；\n desc:预请求，判断当前数据是否能正常在指定库指定表插入",
    "uploadFile": "example:dbchain.uploadFile(file, appCode)；\n desc:dbchain提供了文件上传接口 appCode用于标记此文件属于哪个库\n ",
    "commit": "example:dbchain.commit(fn)；\n desc:打包交易，它会将之前在等待的所有交易全部合并在一起，建议100个以内 \n fn:true || function(){// 执行之后的回调}",
    "querier": "example:dbchain.querier()；\n desc:查询指定库指定表用户数据，详见文档",
    "setMyName": "example:dbchain.setMyName(newName)；\n desc:设置当前用户名",
    "getMyName": "example:dbchain.getMyName()；\n desc:获取当前用户名",

    "getChainId": "example:dbchain.getChainId()；\n desc:获取当前chainId",
    "setChainId": "example:dbchain.setChainId(ChainId)；\n desc:设置chainId",
    "getBaseUrl": "example:dbchain.getBaseUrl()；\n desc:获取当前BaseUrl",
    "setBaseUrl": "example:dbchain.setChainId(BaseUrl)；\n desc:设置BaseUrl",
}